nsmanager/authenticate/urls.py
# authenticate/urls.py

from django.urls import path
from .views import LoginView, LogoutView, RegisterView

app_name = 'authenticate'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

nsmanager/nsmanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls')),
    path('authenticate/', include('authenticate.urls', namespace='authenticate')),  # <- Dodaj ten wpis



]

nsmanager/productapp/urls.py
# myapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, add_product, DeleteProductView, WarehouseCreateView
from . import views
router = DefaultRouter()
router.register(r'productapp', ProductViewSet, basename='product')


app_name = 'productapp'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list_products'),
    path('add-warehouse/', WarehouseCreateView.as_view(), name='add_warehouse'),

    path('api/product/add_product/', add_product, name='add_product'),

    path('product/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:product_id>/delete/', DeleteProductView.as_view(), name='delete_product'),
    path('api/product/<int:product_id>/synchronize/', views.synchronize_product, name='synchronize_product'),
] + router.urls

nsmanager/productapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, Group, Permission

class Company(models.Model):
    name = models.CharField(max_length=255)
    # inne pola charakteryzujące firmę

class Warehouse(models.Model):
    users = models.ManyToManyField(User, related_name='warehouses')
    name = models.CharField(max_length=100, unique=True)

    url = models.TextField()
    credentials = models.TextField()
    
class Product(models.Model):
    sku = models.CharField(max_length=20, unique=True)
    ean = models.CharField(max_length=20, blank=True, null=True)
    name = models.CharField(max_length=200, null=True)
    warehouses = models.ManyToManyField(Warehouse)

    class Meta:
        ordering = ['sku']

class ProductQty(models.Model):
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.DecimalField(max_digits=10, decimal_places=2)
    update_date = models.DateField(auto_now=True)
    wh_product_id = models.CharField(max_length=50)

    class Meta:
        unique_together = ['warehouse', 'product']

class Synchronization(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    last_synch = models.DateField(auto_now=True)
    sum_qty = models.BooleanField(default=False)
    synch = models.BooleanField(default=False)

    class Meta:
        ordering = ['last_synch']

nsmanager/productapp/forms.py
# myapp/forms.py
from django import forms
from .models import Product
from .models import Warehouse,User

class WarehouseForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    
    class Meta:
        model = Warehouse
        fields = ['name', 'url', 'credentials', 'users']
        
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

nsmanager/productapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.views import APIView
from rest_framework import viewsets, permissions
from .models import Product
from .serializers import ProductSerializer
from .forms import ProductForm
from django.views.generic import ListView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.permissions import IsAuthenticated, BasePermission
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import Warehouse
from .forms import WarehouseForm
from django.views import generic
import logging
logger = logging.getLogger(__name__)

class WarehouseCreateView(generic.CreateView):
    form_class = WarehouseForm
    template_name = 'add_warehouse.html'
    success_url = '/'  # Możesz zmienić na odpowiednią wartość
    
    def form_valid(self, form):
        warehouse = form.save(commit=False)
        warehouse.save()  # zapisuje magazyn
        warehouse.users.set(form.cleaned_data['users'])  # przypisuje użytkowników do magazynu
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        logger.info(form.fields['users'].queryset)  # Zaloguj queryset dla użytkowników
        return form


class IsOwnerOrReadOnly(BasePermission):
    def has_object_permission(self, request, view, obj):
        return request.user == obj.owner or request.method in permissions.SAFE_METHODS


class ProductListView(LoginRequiredMixin, ListView):
    login_url = 'authenticate/login/'  # ustaw URL dla strony logowania

    model = Product
    template_name = 'list_products.html'
    context_object_name = 'products'
    paginate_by = 2
    
    def get_queryset(self):
        if self.request.user.is_authenticated and self.request.company:
            return Product.objects.filter(company=self.request.company)
        else:
            return Product.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = context['page_obj'].number
        context['max_page'] = context['paginator'].num_pages
        return context


class ProductViewSet(viewsets.ModelViewSet):

    serializer_class = ProductSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def get_queryset(self):
        return Product.objects.filter(warehouses__users=self.request.user)

    
    def perform_create(self, serializer):
        if self.request.user.has_perm('productapp.add_product'):
            serializer.save()
        else:
            raise permissions.PermissionDenied()

    def perform_update(self, serializer):
        if self.request.user.has_perm('productapp.change_product'):
            serializer.save()
        else:
            raise permissions.PermissionDenied()

    def perform_destroy(self, instance):
        if self.request.user.has_perm('productapp.delete_product'):
            instance.delete()
        else:
            raise permissions.PermissionDenied()


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def add_product(request):
    if request.user.has_perm('productapp.add_product'):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'status': 'success'}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response({'status': 'Permission Denied'}, status=status.HTTP_403_FORBIDDEN)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def synchronize_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST' and request.user.has_perm('productapp.change_product'):
        product.synchronization = not product.synchronization
        product.save()
        return Response({'synchronization': product.synchronization}, status=status.HTTP_200_OK)
    return Response({'status': 'Permission Denied'}, status=status.HTTP_403_FORBIDDEN)

# Podobnie dla innych widoków, jak `edit_product` oraz `DeleteProductView`

@permission_classes([IsAuthenticated])
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if not request.user.has_perm('productapp.change_product'):
        return Response(status=status.HTTP_403_FORBIDDEN)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('productapp:list_products')
    else:
        form = ProductForm(instance=product)
    return render(request, 'edit_product.html', {'form': form})





class DeleteProductView(APIView):
    permission_classes = [IsAuthenticated]

    def delete(self, request, product_id, *args, **kwargs):
        if not request.user.has_perm('productapp.delete_product'):
            return Response({'status': 'error', 'message': 'Forbidden'}, status=status.HTTP_403_FORBIDDEN)
        
        product = get_object_or_404(Product, pk=product_id)
        product.delete()
        
        return Response({'status': 'success'}, status=status.HTTP_200_OK)

nsmanager/productapp/templates/_pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

nsmanager/productapp/templates/add_product.html
<!-- productapp/templates/productapp/add_product.html -->

{% extends 'base_generic.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Zapisz Produkt</button>
    </form>
{% endblock %}

nsmanager/productapp/templates/add_warehouse.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Dodaj hurtownię</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Dodaj</button>
  </form>
{% endblock %}

nsmanager/productapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %} <!-- Zainicjowanie tagów static -->
    <meta charset="UTF-8">
    <title>{% block title %}My App{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'main.js' %}"></script> <!-- Dołączenie pliku main.js -->

</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

nsmanager/productapp/templates/edit_product.html
<!-- productapp/templates/productapp/edit_product.html -->

{% extends 'base_generic.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-warning">Aktualizuj Produkt</button>
    </form>
{% endblock %}

nsmanager/productapp/templates/list_products.html
{% extends 'base_generic.html' %}

{% block content %}
<form method="get" action="">
  <input type="text" name="search" value="{{ request.GET.search }}" placeholder="Search Products">
  <input type="submit" value="Search">
</form>
  <h2>Lista Produktów</h2>
  <a href="{% url 'authenticate:logout' %}" class="btn btn-primary">Wyloguj</a>
  <a href="javascript:void(0)" onclick="addProduct()" class="btn btn-danger">Dodaj Produkt</a>

  <table class="table">
    <thead>
      <tr>
        <th>ID Shoper</th>
        <th>SKU</th>
        <th>EAN</th>
        <th>QTY</th>
        <th>Aktualizacja Ręczna</th>
        <th>Change</th>
        <th>Update Date</th>
        <th>Operation</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
        <tr id="product-{{ product.id }}">
          <td>{{ product.id_shoper }}</td>
          <td>{{ product.sku }}</td>
          <td>{{ product.ean }}</td>
          <td>{{ product.qty }}</td>
          <td id="product-{{ product.id }}-synchronization">{{ product.synchronization }}</td>
          <th>{% csrf_token %} <a href="javascript:void(0)" onclick="synchronizeProduct({{ product.id }})" class="btn btn-success">Synchronizuj</a></th>
          <td>{{ product.update_date }}</td>
          <td>
            <a href="{% url 'productapp:edit_product' product.id %}" class="btn btn-warning">Edytuj</a>
            <a href="javascript:void(0)" 
            data-current-page="{{ current_page }}"
            data-max-page="{{ max_page }}"
            onclick="deleteProduct({{ product.id }}, this)" 
            class="btn btn-danger">Usuń</a>
          </td>
        </tr>

      {% endfor %}
    </tbody>
  </table>
 {% include '_pagination.html' %}

  
  {% include 'modal_add_product.html' %}
{% endblock %}

nsmanager/productapp/templates/logged_out.html
<!-- myapp/templates/myapp/logged_out.html -->

{% extends 'base_generic.html' %}

{% block content %}
  <h2>Zostałeś wylogowany</h2>
  <p>Musisz się <a href="{% url 'login' %}">zalogować</a>, aby uzyskać dostęp do tej strony.</p>
{% endblock %}

nsmanager/productapp/templates/modal_add_product.html
<!-- Modal -->
<div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="productModalLabel">Dodaj Produkt</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="productForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_shoper">ID Shoper</label>
                        <input type="text" class="form-control" id="id_shoper" name="id_shoper" required>
                    </div>
                    <div class="form-group">
                        <label for="sku">SKU</label>
                        <input type="text" class="form-control" id="sku" name="sku" required>
                    </div>
                    <div class="form-group">
                        <label for="ean">EAN</label>
                        <input type="text" class="form-control" id="ean" name="ean" required>
                    </div>
                    <div class="form-group">
                        <label for="qty">QTY</label>
                        <input type="number" class="form-control" id="qty" name="qty" required>
                    </div>
                    <div class="form-group">
                        <label for="synchronization">Synchronization</label>
                        <select class="form-control" id="synchronization" name="synchronization">
                            <!-- Możesz dodać odpowiednie opcje dla synchronizacji tutaj -->
                            <option value="yes">Yes</option>
                            <option value="no">No</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="update_date">Update Date</label>
                        <input type="date" class="form-control" id="update_date" name="update_date">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                <button type="button" class="btn btn-primary" onclick="submitProduct()">Dodaj</button>
            </div>
        </div>
    </div>
</div>